import os

TGTG_EMAIL = os.getenv("TGTG_EMAIL")
WATCHER_FREQUENCY = int(os.getenv("WATCHER_FREQUENCY"))
TELEGRAM_CONFIG_PATH = os.getenv("TELEGRAM_CONFIG_PATH")
LOG_LEVEL = int(os.getenv("LOG_LEVEL"))
